version: '3.9'

services:
  cleanarch-mvc:
    build:
      context: .
      dockerfile: Dockerfile-mvc
    ports:
      - "8888:80"

  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile-sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssword
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: null
